### PR TITLE
Add nitorch package data

### PR DESCRIPTION
**Pull request by brudfors**
#24

### CODE REVIEW

**Comment by brudfors** [comment]
@balbasty, I did it not the way you wanted... Seems as if people do not like downloading during package install:

https://stackoverflow.com/questions/37513279/using-setuptools-how-can-i-download-external-data-upon-installation

I put it in core.utils for now. Also, there is probably a neater way of getting the data directory, which will not break if we change the package structure.

**Comment by balbasty** [comment]
Ok that's fine!
Can you just move your utilities to pyutils? Utils is for torch utilities (the name is not very clear...)

**Comment by balbasty** [comment]
Also add the dependency to wget in setup.py (install_requires=[...])

**Comment by brudfors** [comment]
Done.

**Review by balbasty — APPROVED** [review]
Looks good, thanks :)
(Something to keep in mind: if we start producing more atlases it will be useful to have a good naming convention to differentiate them)

**Comment by brudfors** [comment]
Thanks :)

Yes, good idea :+1:

**Pull request merged**
