### PR TITLE
Added augmentation to neural network models.

### LINKED ISSUE #40: Add data augmentation.
Data augmentation is useful in general for training NNs. I propose implementation of a new ImageAugmentor class that allows for augmenting images. But @balbasty might want it more general, so maybe start with Augmentor as the base class? This object could then be imported into a data iterator that loads batches for training/validation/testing.

My questions are:

1. Where should we put this object?
2. What type of augmentation should we include? I guess, flips, affine transformations, nonlinear transformations, intensity transformations, etc.

### PR DESCRIPTION
**Pull request by brudfors**
Closes #40.

I got a recursive import error, so I decided to move segmentation.py to a new folder in nn, called models. 

A function called add_augmenters is now part of the base nn module, supposed to be populated by a user. As augmentation is quite task-specific, I put it in segmentation.py for segmentation augmentation. 

This is how it could be added to a segmentation model:

```py
from nitorch.nn.models.segmentation import augmentation
model.add_augmenter(lambda x, y: augmentation('warp', x, y))
model.add_augmenter(lambda x, y: augmentation('inu', x, y))
model.add_augmenter(lambda x, y: augmentation('noise', x, y))
```

@balbasty, what do you think of the implementation and structure?

### CODE REVIEW

**Comment by balbasty** [comment]
The circular import just comes from your augmentation function in the segmentation file no? Why not keep SegNet in modules and have the augmentation function in generators?

**Comment by brudfors** [comment]
> The circular import just comes from your augmentation function in the segmentation file no? Why not keep SegNet in modules and have the augmentation function in generators?
> 
> i have added comments directly to the commit

I can't seem to find your comments in the commit?

**Comment by brudfors** [comment]
Moved the augmentation into a new module in generators.

**Comment by balbasty** [comment]
> > The circular import just comes from your augmentation function in the segmentation file no? Why not keep SegNet in modules and have the augmentation function in generators?
> 
> > 
> 
> > i have added comments directly to the commit
> 
> 
> 
> I can't seem to find your comments in the commit?

There are 8 comments that appear on this PR on my side. Can you see them? That's what I was referring to

**Comment by brudfors** [comment]
> > > The circular import just comes from your augmentation function in the segmentation file no? Why not keep SegNet in modules and have the augmentation function in generators?
> > 
> > 
> > > 
> > 
> > 
> > > i have added comments directly to the commit
> > 
> > 
> > I can't seem to find your comments in the commit?
> 
> There are 8 comments that appear on this PR on my side. Can you see them? That's what I was referring to

Do you mean the comment are on the code in the commit, which I can reach by, on this page, clicking Commits and then clicking on my initial commit? No, I cannot see any comments there.

**Pull request merged**
